### ISSUE TITLE
Tab bar sorting function

### ISSUE THREAD

**Issue by DasFlogetier** [loilo/auto-group-tabs#41] opened 2023-06-22 08:51 UTC
First of all, this extension is amazing. 
I'm a bit of a freak when it comes to organization and this piece of code is just what I needed.

I might have an idea or feature request. 
It would be great to have an option where all groups jump to the beginning of the tab bar.
Maybe through a switch with a filter or a sorting function where you can sort the created groups (A-Z, custom, ...) and have that order reflected in the tab bar.

**Comment by loilo** [comment] 2023-06-22 13:48
Hey @DasFlogetier, thanks for the suggestion.
This is the feature I want to implement next, although I'm not sure when I'll find the time to work on the project.

I'll close this issue though, as it is a duplicate of #24 and #12.

**Closed by loilo** 2023-06-22 13:48 UTC
