### ISSUE TITLE
New tabs don't re-evaluate when opened in a group

### ISSUE THREAD

**Issue by itzteajay-glitch** [loilo/auto-group-tabs#5] opened 2021-05-13 15:10 UTC
First off this extension is awesome! I have lots of groups set up with filters for work and one of them is monitoring and the other is jira. When I click on links (like to a jira) in my monitoring tool it opens a new tab. This new tab just stays in my monitoring group even though it meets the qualifiers to be loaded into another group. Is there anything that can be down to say remove and reapply your chrome filter rules on any new tab that's open regardless of if it's in a group or not?

Thanks again for this awesome extension! I look forward to seeing it grow :)

**Comment by loilo** [comment] 2021-05-13 18:53
Hey there, thanks for the feedback. Glad the extension is helping. 🙂 
What you're describing is (currently) by design — I decided not to touch tabs that are already grouped (as well as pinned tabs, for example). This is how I personally prefer it to work.

However, I can see how preferences can be different for others. In case I'll be adding options to this extension, I'll definitely include a setting like the behavior you described. Not sure about the timeframe though. 😉

**Comment by itzteajay-glitch** [comment] 2021-05-13 19:04
Thanks for your quick response and for considering my request! :D

**Comment by loilo** [comment] 2022-02-24 08:21
Auto-Group Tabs v0.0.6 was just released and should fix this – tabs should now be grouped into their configured categorization very reliably, even if they were in a different group before.

I'll close this now, but feel free to re-open if anything does still not work as expected.

**Closed by loilo** 2022-02-24 08:21 UTC
