### ISSUE TITLE
Auto Group Tabs Not responding anymore

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [loilo/auto-group-tabs#16] opened 2022-02-25 08:49 UTC
Hello, thx a lot for this awesome plugin. It really makes the grouping feature into something useful.

Now after a computer restart, all my configured groups are not visible anymore and I can also not create new groups. The options UI appears to be kind of frozen.

<img width="408" alt="Screenshot 2022-02-25 at 09 43 48" src="https://user-images.githubusercontent.com/1157580/155684263-bf423766-fdc4-4435-9903-e56addaf92db.png">

A reinstall of the plugin also did not solve this.

I'm a developer myself, so if you walk me through how to enable some debug logs or where to find them for chrome extensions I'm gladly assisting analysing the issue.

Thx a lot!
Andreas

**Comment by loilo** [comment] 2022-02-25 09:04
Big oof.

Yes, an update was released yesterday and I thought I had tested it thoroughly enough...
So first things first: _What_ exactly appears to be frozen?

To receive your groups programmatically, you can go to chrome://extensions, into the details of the extension and click the "Service Worker" link. This will open the browser's devtools specifically for the service worker which runs the tab to group assignments.

There in the console, run `(await chrome.storage.sync.get(['groups'])).groups` to receive the groups stored for the extension. There's not really a thing I could make of that information, but at least you could take a look if the groups are still stored? (That said, if you saved new groups, those are probably overridden anyway...)

(There was a major change in how groups are stored in the current release. Previously, they were stored as a JSON string, now they are stored directly as an object. However, if the extension gets a string from that storage, it will first parse it as JSON, specifically to preserve backward compatibility. And this process _seems_ to work, I've just tested it on my machine again...)

**Comment by Andreas-Schoenefeldt** [comment] 2022-02-25 12:43
Ha, cheers Mate,

it's a null pointer exception I would say:

<img width="1065" alt="Screenshot 2022-02-25 at 13 41 02" src="https://user-images.githubusercontent.com/1157580/155716802-a7425f60-d878-42fb-872a-2131faa83dd0.png">

<img width="475" alt="Screenshot 2022-02-25 at 13 40 57" src="https://user-images.githubusercontent.com/1157580/155716835-b5c2096a-75e5-4743-99fc-1f2f829e5d9d.png">

In my original screenshot, I'm not able to save any group new - I guess it simply broke something.

if i try
```
await chrome.storage.sync.get(['groups'])
```

I receive `undefined`.

Thx a lot for your help!

**Comment by Andreas-Schoenefeldt** [comment] 2022-02-25 12:46
P.S.: I'm running  Iron browser (chrome without the tracking) Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by loilo** [comment] 2022-02-25 12:47
Well that is an interesting information.
Because whenever I'm testing what you did there, I won't get an error because  `await chrome.storage.sync.get(['groups'])` (and `'groups'` can be anything here) always returns an empty object, not undefined.

I'll install the Iron browser and take a look at this. 🙂

**Comment by loilo** [comment] 2022-02-25 12:54
Okay, I'm not able to reproduce the issue there, however the downloaded version is SRWare Iron 97, which is quite some versions ahead of yours.

Can you confirm that `await chrome.storage.sync.get(['groups'])` returns `undefined` in your extension service worker devtools? In that case, I could add a fallback.

**Comment by Andreas-Schoenefeldt** [comment] 2022-02-25 14:01
Jep, I confirm - it's `undefined`

**Comment by Andreas-Schoenefeldt** [comment] 2022-02-25 14:05
Ok, I updated Iron and it works now as intended. Looks like the missing auto update got me here. 

From my side you can ignore the issue now, if you like - I guess not many other people will run around with an outdated browser here.

Thx a lot for your swift help!
Andreas

**Comment by loilo** [comment] 2022-02-25 14:09
Great to hear, happy to help!

I have [committed](https://github.com/loilo/auto-group-tabs/commit/c2638c2fcd932f23bce776e783e5b6be573a468a) the fallback (it's literally [two characters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)) and will include the fix in the next release. However, now that you're done with the issue, I'll probably not do an extra release for this bugfix alone (just because it will induce a new review process etc etc). 🙂

**Closed by loilo** 2022-02-25 14:09 UTC
