### ISSUE TITLE
New tab sometimes doesn't group 

### ISSUE THREAD

**Issue by petrvecera** [loilo/auto-group-tabs#15] opened 2022-02-04 14:37 UTC
I have run into a weird issue that some tabs sometimes doesn't group. It happens "randomly" and usually when I click on a hyperlink. The original tab is not grouped. I can't figure out the steps to reproduce. I will try to work on them. 

![image](https://user-images.githubusercontent.com/8086995/152547080-1187047b-4c96-4c7a-8576-422e8a53fb26.png)
The gitlab tab has been opened from the first tab - Jira confluence. And for some reason didn't get grouped with other gitlab tabs. When I clicked on another link it properly grouped. 

I am trying to report this in case - someone has the similar experience and would be able to find the steps to reproduce. 

Btw thank you for the extension. It's amazing!

**Comment by loilo** [comment] 2022-02-04 15:34
Thanks for the report. Yes, I'm aware of the issue (aka I have experienced it myself) but I have no idea how to reproduce as well. 😁

**Comment by loilo** [comment] 2022-02-14 17:48
Do you have concrete hints that support this?
(Not sure if I would do anything concrete about it anyway though. I'm currently deep inside a full rewrite of the extensions' underlying technology, which I hope will greatly increase overall reliability of the extension.)

**Comment by petrvecera** [comment] 2022-02-14 20:23
I noticed that it can happen on the same link. After long time - first click doesn't group. I close that tab - click again - it groups. 
The difference between those 2 actions is that in the second case it loads much faster. In the first click is slow - I might have ~100 tabs open. 

Would it be possible that the extension code is executed before the tab link is properly loaded?

**Comment by loilo** [comment] 2022-02-14 20:33
I can't really rule this out completely as the extension is based on Chrome's Extension API which fires an event for every URL change of any tab, so if the reason is what you describe, it would be a bug on Chrome's side (which I really don't think).

However, working on the extension right now I have already encountered some cases where my assumptions didn't hold true about how tabs are handled by Chrome resp. how they're represented in the Extension API. So let's see whether the next extension release will fix these issues.

**Comment by loilo** [comment] 2022-02-24 08:13
Auto-Group Tabs v0.0.6 was just released and should fix this problem – tabs should now be categorized into their configured groups very reliably.
I'll close this now, but feel free to re-open if anything does still not work as expected.

**Closed by loilo** 2022-02-24 08:13 UTC
