### ISSUE TITLE
On start browser the names and color are deleted

### ISSUE THREAD

**Issue by javier8340** [loilo/auto-group-tabs#20] opened 2022-03-28 07:44 UTC
Hi, i have a problem when I start the browser with auto open tabs, some groups are renamed to empty string and color set to first.

**Comment by loilo** [comment] 2022-03-28 07:52
Oh, that's weird, haven't heard of that one yet. Which browser + version are you using exactly?

**Comment by loilo** [comment] 2022-03-28 08:00
And the issue happens on both browsers? Do you have the same tab groups configured on both?

**Comment by javier8340** [comment] 2022-03-28 08:08
> And the issue happens on both browsers? Do you have the same tab groups configured on both?

No, are diferents groups.

**Comment by loilo** [comment] 2022-03-28 08:11
And it happens on both browsers?

**Comment by javier8340** [comment] 2022-03-28 08:12
Yhea

**Comment by loilo** [comment] 2022-03-28 08:17
Oof. Okay, since I haven't encountered this problem yet, I guess I won't be able to reproduce it without knowing your group configurations... If you don't mind, would you share them?

If you would, here's the fastest way to do so:

1. Go to the `chrome://extensions` URL in your browser.
2. Turn on the "Developer mode" switch in the upper right of the screen.
3. Scroll to the Auto Group Tabs extension and click on the "Details" button.
4. Find and click the blue "Service Worker" link.
5. In the developer tools window that opens, paste the following command into the console:
   ```js
   copy(await chrome.storage.sync.get('groups'))
   ```

This will copy your groups configuration to your clipboard which you could paste here.

**Comment by javier8340** [comment] 2022-03-29 07:25
{
    "groups": [
        {
            "color": "yellow",
            "id": "92dc87ec-1a3d-4b43-b6e6-4e8c238ec61b",
            "matchers": [
                "https://docs.google.com/spreadsheets/d/idSpreadsheet*"
            ],
            "title": ""
        },
        {
            "color": "red",
            "id": "458eff9",
            "matchers": [
                "myweb.com"
            ],
            "title": "Snow"
        },
        {
            "color": "green",
            "id": "509dde7",
            "matchers": [
                "docs.google.com"
            ],
            "title": "Docs"
        }
    ]
}

**Comment by loilo** [comment] 2022-03-29 07:46
Thanks. Still can't reproduce with that configuration unfortunately. For me, everything works fine...

<img width="680" alt="Screenshot of two browser tabs, one in a red tab group named 'Snow'" src="https://user-images.githubusercontent.com/1922624/160560198-703bf275-2625-4a04-97e1-5ff56973c4c7.png">

Does this happen for you everytime you restart your browser? Otherwise, do you have reliable steps to reproduce the behavior on your machine?

**Comment by javier8340** [comment] 2022-03-29 09:35
when I restart the computer and open the browser, sometimes the tabs gets crazy (important to have open last tabs option on)

**Comment by loilo** [comment] 2022-03-29 11:30
Well this sucks. I cannot reproduce your issue and your configuration does not show anything suspicious. You could try to uninstall & reinstall the extension to start from a clean slate, but I'm not too confident that it will help.

Very sorry I'm not really able to help you at the moment. I'll keep this issue open, maybe others will come up with the same problem and we can get more information about why this happens...

**Comment by javier8340** [comment] 2022-03-29 11:40
the problem is that happens on 2 browsers (one on virtual machine) so must can be replicated with time i guess

**Comment by loilo** [comment] 2022-03-29 11:41
Let's hope so.

**Comment by vpashovski** [comment] 2022-04-14 06:17
Hello, same issue here.
What I'm doing is closing the browser with opened tabs in groups (tab groups are minimized but it is not required). After opening the browser again they are refreshing (flashing) and sometimes are reset.
Chrome browser is Version 100.0.4896.88 (Official Build) (64-bit).
Here is a video with the result: https://imgur.com/a/HI6JpCA

**Comment by loilo** [comment] 2022-04-30 13:03
Just a heads-up: I got a crucial clue regarding reproduction via email. It seems that the problem is reliably reproducible if, on browser startup, multiple windows with the same tab group are restored.

Let's hope that this brings me closer to a fix. 🙂

**Closed** 2022-05-01 10:09 UTC
Labels: needs reproduction

**Comment by loilo** [comment] 2022-05-01 10:11
Alright, this should be fixed now. 🎉 
New extension version has been submitted for review and should be automatically rolled out some time this week. Check for extension version 0.0.9.

**Comment by loilo** [comment] 2022-05-04 09:16
FYI: Version 0.0.9 has officially been released a couple of hours ago. You can wait for it to update automatically or go to Extension (chrome://extensions/?id=danncghahncanipdoajmakdbeaophenb) and press the "Update" button manually.
